use chrono::{Duration, TimeZone, Utc};
use simple_blog::{
    application::site_compiler::{PublicRedirect, SiteCompiler, SiteSnapshotV1},
    domain::{
        content::{Content, ContentId, ContentKind, Publication, Slug, Tag},
        theme::{Locale, NavigationItem, SiteSettings},
    },
    release::{PreparedRelease, ReleaseRoute},
};

fn content(
    id: i64,
    title: &str,
    slug: &str,
    publication: Publication,
    updated_offset: i64,
) -> Content {
    let created_at = Utc.with_ymd_and_hms(2026, 9, 1, 0, 0, 0).unwrap();
    Content {
        id: ContentId::from_i64(id),
        kind: ContentKind::Post,
        title: title.into(),
        slug: Slug::parse(slug).unwrap(),
        summary: format!("Summary for {title}"),
        body_markdown: format!("# {title}\n\nBody for {title}."),
        body_html: format!("<h1>{title}</h1><p>Body for {title}.</p>"),
        tags: vec![Tag {
            name: "Rust".into(),
            slug: Slug::parse("rust").unwrap(),
        }],
        cover_media_id: None,
        seo_title: None,
        seo_description: None,
        publication,
        version: 1,
        created_at,
        updated_at: created_at + Duration::minutes(updated_offset),
        deleted_at: None,
    }
}

fn snapshot(contents: Vec<Content>) -> SiteSnapshotV1 {
    SiteSnapshotV1 {
        public_revision: 17,
        effective_at: Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap(),
        settings: SiteSettings {
            site_title: "Portable writing".into(),
            site_description: "A site generated by the shared core".into(),
            locale: Locale::En,
            logo_media_id: None,
            favicon_media_id: None,
            custom_css: "body { color: #222; }".into(),
            timezone: "UTC".into(),
            author_name: String::new(),
            custom_css_backup: None,
        },
        navigation: Vec::new(),
        contents,
        redirects: vec![PublicRedirect {
            from: Slug::parse("before").unwrap(),
            to: Slug::parse("published").unwrap(),
        }],
        media: Vec::new(),
    }
}

fn body<'a>(release: &'a PreparedRelease, path: &str) -> &'a str {
    let ReleaseRoute::Asset { object_id, .. } = &release.manifest.routes[path] else {
        panic!("{path} is not an asset")
    };
    std::str::from_utf8(&release.objects[object_id]).unwrap()
}

#[test]
fn compiler_emits_the_complete_public_surface_without_non_visible_content() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let release = SiteCompiler::embedded()
        .unwrap()
        .compile(
            &snapshot(vec![
                content(
                    1,
                    "Published",
                    "published",
                    Publication::Public {
                        publish_at: now - Duration::hours(1),
                    },
                    1,
                ),
                content(2, "Private", "private", Publication::Draft, 2),
                content(
                    3,
                    "Future",
                    "future",
                    Publication::Public {
                        publish_at: now + Duration::hours(1),
                    },
                    3,
                ),
            ]),
            "https://writing.example",
            None,
        )
        .unwrap();

    for path in [
        "/",
        "/published/",
        "/archive/",
        "/tag/",
        "/tag/rust/",
        "/tag/rust/feed.xml",
        "/search/",
        "/feed.xml",
        "/sitemap.xml",
        "/robots.txt",
        "/404/",
        "/assets/site.css",
        "/assets/like.js",
        "/assets/prefs.js",
        "/assets/search.js",
        "/assets/search-index.json",
    ] {
        assert!(release.manifest.routes.contains_key(path), "missing {path}");
    }
    assert!(matches!(
        release.manifest.routes["/before/"],
        ReleaseRoute::Redirect { status: 301, .. }
    ));
    assert!(matches!(
        release.manifest.routes["/published"],
        ReleaseRoute::Redirect { status: 308, .. }
    ));
    assert!(!release.manifest.routes.contains_key("/private/"));
    assert!(!release.manifest.routes.contains_key("/future/"));
    assert_eq!(release.manifest.routes["/404/"].status(), Some(404));
    assert_eq!(
        release.manifest.routes["/published/"].last_modified(),
        Some(Utc.with_ymd_and_hms(2026, 9, 1, 0, 1, 0).unwrap())
    );

    let home = body(&release, "/");
    assert!(home.contains("Published"));
    assert!(!home.contains("Private"));
    assert!(!home.contains("Future"));
    assert!(home.contains("https:&#x2f;&#x2f;writing.example&#x2f;"));
    assert!(body(&release, "/feed.xml").contains("Body for Published"));
    assert!(body(&release, "/sitemap.xml").contains("&#x2f;published&#x2f;"));
    assert!(body(&release, "/assets/search-index.json").contains("Published"));
}

#[test]
fn archive_never_silently_omits_older_posts() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let posts = (1..=101)
        .map(|id| {
            content(
                id,
                &format!("Post {id}"),
                &format!("post-{id}"),
                Publication::Public {
                    publish_at: now - Duration::minutes(id),
                },
                id,
            )
        })
        .collect();

    let release = SiteCompiler::embedded()
        .unwrap()
        .compile(&snapshot(posts), "https://writing.example", None)
        .unwrap();
    let archive = body(&release, "/archive/");

    assert!(archive.contains("Post 1"));
    assert!(archive.contains("Post 101"));
}

#[test]
fn feed_updated_tracks_the_most_recent_edit_not_publication_order() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let newest_publication = content(
        1,
        "Newly published",
        "newly-published",
        Publication::Public {
            publish_at: now - Duration::hours(1),
        },
        1,
    );
    let older_but_edited = content(
        2,
        "Recently edited",
        "recently-edited",
        Publication::Public {
            publish_at: now - Duration::days(1),
        },
        120,
    );

    let release = SiteCompiler::embedded()
        .unwrap()
        .compile(
            &snapshot(vec![newest_publication, older_but_edited]),
            "https://writing.example",
            None,
        )
        .unwrap();
    let feed_header = body(&release, "/feed.xml").split("<entry>").next().unwrap();

    assert!(feed_header.contains("<updated>2026-09-01T02:00:00Z</updated>"));
}

#[test]
fn generated_url_attributes_rely_on_contextual_escaping() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let mut site = snapshot(vec![content(
        1,
        "Escaped links",
        "escaped-links",
        Publication::Public { publish_at: now },
        1,
    )]);
    site.navigation.push(NavigationItem {
        id: 1,
        label: "Query link".into(),
        destination: "https://example.com/read?first=1&second=2".into(),
        is_external: true,
        position: 0,
    });

    let release = SiteCompiler::embedded()
        .unwrap()
        .compile(&site, "https://writing.example", None)
        .unwrap();

    assert!(body(&release, "/").contains("first=1&amp;second=2"));
}

#[test]
fn compiler_output_is_deterministic_for_equivalent_snapshot_orderings() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let first = content(
        1,
        "First",
        "first",
        Publication::Public {
            publish_at: now - Duration::hours(2),
        },
        1,
    );
    let second = content(
        2,
        "Second",
        "second",
        Publication::Public {
            publish_at: now - Duration::hours(1),
        },
        2,
    );
    let compiler = SiteCompiler::embedded().unwrap();

    let ordered = compiler
        .compile(
            &snapshot(vec![first.clone(), second.clone()]),
            "https://writing.example",
            None,
        )
        .unwrap();
    let reversed = compiler
        .compile(
            &snapshot(vec![second, first]),
            "https://writing.example/",
            None,
        )
        .unwrap();

    assert_eq!(ordered.id, reversed.id);
    assert_eq!(ordered.manifest_bytes, reversed.manifest_bytes);
    assert_eq!(ordered.objects, reversed.objects);
}

#[test]
fn compiler_reuses_unchanged_objects_without_changing_clean_build_semantics() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let compiler = SiteCompiler::embedded().unwrap();
    let original = content(
        1,
        "Original",
        "original",
        Publication::Public {
            publish_at: now - Duration::hours(1),
        },
        1,
    );
    let base = compiler
        .compile(
            &snapshot(vec![original.clone()]),
            "https://writing.example",
            None,
        )
        .unwrap();
    let mut changed = original;
    changed.title = "Changed".into();
    changed.body_html = "<p>Changed body</p>".into();
    changed.updated_at += Duration::minutes(1);
    let mut next_snapshot = snapshot(vec![changed]);
    next_snapshot.public_revision = 18;

    let incremental = compiler
        .compile(
            &next_snapshot,
            "https://writing.example",
            Some(&base.manifest),
        )
        .unwrap();
    let clean = compiler
        .compile(&next_snapshot, "https://writing.example", None)
        .unwrap();

    assert_eq!(incremental.id, clean.id);
    assert_eq!(incremental.manifest, clean.manifest);
    assert!(incremental.objects.len() < clean.objects.len());
}

#[test]
fn incremental_compiler_prunes_content_tag_and_redirect_routes_absent_from_the_snapshot() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let compiler = SiteCompiler::embedded().unwrap();
    let original = content(
        1,
        "Original",
        "original",
        Publication::Public {
            publish_at: now - Duration::hours(1),
        },
        1,
    );
    let base = compiler
        .compile(
            &snapshot(vec![original.clone()]),
            "https://writing.example",
            None,
        )
        .unwrap();

    let mut hidden = original;
    hidden.publication = Publication::Draft;
    let mut next_snapshot = snapshot(vec![hidden]);
    next_snapshot.public_revision = 18;
    next_snapshot.redirects.clear();

    let incremental = compiler
        .compile(
            &next_snapshot,
            "https://writing.example",
            Some(&base.manifest),
        )
        .unwrap();
    let clean = compiler
        .compile(&next_snapshot, "https://writing.example", None)
        .unwrap();

    assert_eq!(incremental.id, clean.id);
    assert_eq!(incremental.manifest, clean.manifest);
    assert!(incremental.objects.len() < clean.objects.len());
    for removed in [
        "/original",
        "/original/",
        "/tag/rust",
        "/tag/rust/",
        "/before",
        "/before/",
    ] {
        assert!(
            !incremental.manifest.routes.contains_key(removed),
            "stale route survived incremental compilation: {removed}"
        );
    }
}
use scraper::{Html, Selector};
use simple_blog::domain::media::{MediaAsset, MediaId, MediaVariant};

fn tagged(mut content: Content, names: &[&str]) -> Content {
    content.tags = names
        .iter()
        .map(|name| Tag {
            name: (*name).to_owned(),
            slug: Slug::parse(name.to_lowercase()).unwrap(),
        })
        .collect();
    content
}

fn published_post(id: i64, title: &str, slug: &str, minutes_ago: i64) -> Content {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    content(
        id,
        title,
        slug,
        Publication::Public {
            publish_at: now - Duration::minutes(minutes_ago),
        },
        1,
    )
}

fn compile(contents: Vec<Content>) -> PreparedRelease {
    SiteCompiler::embedded()
        .unwrap()
        .compile(&snapshot(contents), "https://writing.example", None)
        .unwrap()
}

fn attribute<'a>(document: &'a Html, selector: &str, name: &str) -> Vec<&'a str> {
    let selector = Selector::parse(selector).unwrap();
    document
        .select(&selector)
        .filter_map(|element| element.value().attr(name))
        .collect()
}

fn texts(document: &Html, selector: &str) -> Vec<String> {
    let selector = Selector::parse(selector).unwrap();
    document
        .select(&selector)
        .map(|element| element.text().collect::<String>().trim().to_owned())
        .collect()
}

#[test]
fn not_found_and_index_pages_are_localized() {
    let mut site = snapshot(vec![published_post(1, "掲載", "posted", 5)]);
    site.settings.locale = Locale::Ja;
    let release = SiteCompiler::embedded()
        .unwrap()
        .compile(&site, "https://writing.example", None)
        .unwrap();

    let not_found = body(&release, "/404/");
    assert!(not_found.contains("ページが見つかりません"));
    assert!(not_found.contains("ホームへ戻る"));
    assert!(!not_found.contains("Return home"));
    assert!(not_found.contains("<title>ページが見つかりません — Portable writing</title>"));

    let archive = Html::parse_document(body(&release, "/archive/"));
    assert_eq!(
        attribute(&archive, "meta[name=description]", "content"),
        ["公開済みの文章を年ごとに。"]
    );
    assert_eq!(
        attribute(&archive, "header.site-header nav", "aria-label"),
        Vec::<&str>::new()
    );
    let tag = Html::parse_document(body(&release, "/tag/rust/"));
    assert_eq!(
        attribute(&tag, "meta[name=description]", "content"),
        ["「Rust」のタグが付いた文章。"]
    );
    let search = Html::parse_document(body(&release, "/search/"));
    assert_eq!(
        attribute(&search, "meta[name=description]", "content"),
        ["記事とページを検索。"]
    );
    let with_navigation = {
        let mut site = site;
        site.navigation.push(NavigationItem {
            id: 1,
            label: "About".into(),
            destination: "/about/".into(),
            is_external: false,
            position: 0,
        });
        SiteCompiler::embedded()
            .unwrap()
            .compile(&site, "https://writing.example", None)
            .unwrap()
    };
    let home = Html::parse_document(body(&with_navigation, "/"));
    assert_eq!(
        attribute(&home, "header.site-header nav", "aria-label"),
        ["メイン"]
    );
}

#[test]
fn feed_is_valid_atom_with_author_categories_and_alternate_links() {
    let release = compile(vec![tagged(
        published_post(1, "Published", "published", 60),
        &["Rust", "Writing"],
    )]);
    let feed = body(&release, "/feed.xml");

    let author = feed
        .find("<author><name>Portable writing</name></author>")
        .unwrap();
    let entry = feed.find("<entry>").unwrap();
    assert!(author < entry, "the feed-level author precedes every entry");
    assert!(feed.contains("<subtitle>A site generated by the shared core</subtitle>"));
    assert!(feed.contains("<category term=\"rust\" label=\"Rust\"/>"));
    assert!(feed.contains("<category term=\"writing\" label=\"Writing\"/>"));
    assert!(feed.contains("rel=\"alternate\" type=\"text/html\""));
    assert!(feed.contains("https:&#x2f;&#x2f;writing.example&#x2f;published&#x2f;"));
}

#[test]
fn every_tag_has_its_own_feed_with_autodiscovery() {
    let mut page = published_post(2, "About", "about", 30);
    page.kind = ContentKind::Page;
    let release = compile(vec![
        tagged(published_post(1, "Post", "post", 60), &["Rust"]),
        tagged(page, &["Rust"]),
    ]);

    let ReleaseRoute::Asset { content_type, .. } = &release.manifest.routes["/tag/rust/feed.xml"]
    else {
        panic!("tag feed must be an asset")
    };
    assert_eq!(content_type, "application/atom+xml; charset=utf-8");
    let feed = body(&release, "/tag/rust/feed.xml");
    assert!(feed.contains("<id>https:&#x2f;&#x2f;writing.example&#x2f;tag&#x2f;rust&#x2f;</id>"));
    assert!(feed.contains("<title>Portable writing — #Rust</title>"));
    assert!(feed.contains("Post"));
    assert!(
        !feed.contains("<title>About</title>"),
        "pages stay out of tag feeds"
    );
    let tag_page = body(&release, "/tag/rust/");
    assert!(
        tag_page.contains("About"),
        "pages still appear on the tag page"
    );
    let document = Html::parse_document(tag_page);
    let alternates = attribute(
        &document,
        "link[rel=alternate][type='application/atom+xml']",
        "href",
    );
    assert_eq!(alternates, ["/feed.xml", "/tag/rust/feed.xml"]);

    let mut without = snapshot(vec![published_post(1, "Post", "post", 60)]);
    without.contents[0].tags.clear();
    without.public_revision = 18;
    let incremental = SiteCompiler::embedded()
        .unwrap()
        .compile(&without, "https://writing.example", Some(&release.manifest))
        .unwrap();
    assert!(
        !incremental
            .manifest
            .routes
            .contains_key("/tag/rust/feed.xml")
    );
    assert!(!incremental.manifest.routes.contains_key("/tag/rust/"));
}

#[test]
fn tag_index_lists_every_tag_by_count_then_name() {
    let release = compile(vec![
        tagged(published_post(1, "One", "one", 10), &["Rust", "Zig"]),
        tagged(
            published_post(2, "Two", "two", 20),
            &["Rust", "Zig", "Axum"],
        ),
        tagged(published_post(3, "Three", "three", 30), &["Rust", "Zig"]),
    ]);

    assert!(matches!(
        release.manifest.routes["/tag"],
        ReleaseRoute::Redirect { status: 308, .. }
    ));
    let index = Html::parse_document(body(&release, "/tag/"));
    assert_eq!(
        attribute(&index, "table.tag-list a", "href"),
        ["/tag/rust/", "/tag/zig/", "/tag/axum/"]
    );
    assert_eq!(
        texts(&index, "table.tag-list td:last-child"),
        ["3", "3", "1"]
    );
    assert_eq!(texts(&index, "h1"), ["Tags"]);
    assert!(attribute(&index, "footer.site-footer a", "href").contains(&"/tag/"));

    let empty = compile(vec![{
        let mut post = published_post(1, "Untagged", "untagged", 10);
        post.tags.clear();
        post
    }]);
    assert!(body(&empty, "/tag/").contains("No tags yet."));
}

#[test]
fn sitemap_covers_index_and_tag_pages_with_last_modified_dates() {
    let posts = (1..=21)
        .map(|id| published_post(id, &format!("Post {id}"), &format!("post-{id}"), id))
        .collect();
    let release = compile(posts);
    let sitemap = body(&release, "/sitemap.xml");

    for path in [
        "&#x2f;archive&#x2f;",
        "&#x2f;tag&#x2f;</loc>",
        "&#x2f;tag&#x2f;rust&#x2f;",
        "&#x2f;page&#x2f;2&#x2f;",
        "&#x2f;post-21&#x2f;",
    ] {
        assert!(sitemap.contains(path), "sitemap lacks {path}");
    }
    assert!(sitemap.contains(
        "<url><loc>https:&#x2f;&#x2f;writing.example&#x2f;</loc><lastmod>2026-09-01</lastmod></url>"
    ));
}

#[test]
fn home_is_paginated_in_twenties_with_rel_links() {
    let posts = (1..=45)
        .map(|id| published_post(id, &format!("Post {id}"), &format!("post-{id}"), id))
        .collect();
    let release = compile(posts);

    for path in ["/", "/page/2/", "/page/3/"] {
        assert!(release.manifest.routes.contains_key(path), "missing {path}");
    }
    assert!(!release.manifest.routes.contains_key("/page/4/"));
    for redirect in ["/page/1/", "/page/1", "/page/2", "/page/3"] {
        assert!(
            matches!(
                release.manifest.routes[redirect],
                ReleaseRoute::Redirect { status: 308, .. }
            ),
            "{redirect} must redirect"
        );
    }

    let first = Html::parse_document(body(&release, "/"));
    assert_eq!(texts(&first, "article.post-card h2").len(), 20);
    assert_eq!(attribute(&first, "link[rel=next]", "href"), ["/page/2/"]);
    assert!(attribute(&first, "link[rel=prev]", "href").is_empty());
    assert_eq!(
        attribute(&first, "nav.pager a[rel=next]", "href"),
        ["/page/2/"]
    );
    assert_eq!(texts(&first, "nav.pager .pager-status"), ["Page 1 of 3"]);
    assert!(attribute(&first, "script[type='application/ld+json']", "type").len() == 1);

    let second = Html::parse_document(body(&release, "/page/2/"));
    assert_eq!(attribute(&second, "link[rel=prev]", "href"), ["/"]);
    assert_eq!(attribute(&second, "link[rel=next]", "href"), ["/page/3/"]);
    assert_eq!(attribute(&second, "nav.pager a[rel=prev]", "href"), ["/"]);
    assert_eq!(
        attribute(&second, "link[rel=canonical]", "href"),
        ["https://writing.example/page/2/"]
    );
    assert_eq!(texts(&second, "title"), ["Page 2 — Portable writing"]);
    assert_eq!(
        attribute(&second, "meta[name=description]", "content"),
        ["A site generated by the shared core"]
    );
    assert!(attribute(&second, "script[type='application/ld+json']", "type").is_empty());

    let third = Html::parse_document(body(&release, "/page/3/"));
    assert_eq!(texts(&third, "article.post-card h2").len(), 5);
    assert!(attribute(&third, "link[rel=next]", "href").is_empty());
    assert_eq!(
        attribute(&third, "nav.pager a.post-nav-older", "href"),
        ["/archive/"]
    );
}

#[test]
fn home_with_at_most_twenty_posts_has_no_page_routes_but_links_the_archive() {
    let release = compile(vec![
        published_post(1, "One", "one", 1),
        published_post(2, "Two", "two", 2),
    ]);

    assert!(!release.manifest.routes.contains_key("/page/2/"));
    assert!(matches!(
        release.manifest.routes["/page/1/"],
        ReleaseRoute::Redirect { status: 308, .. }
    ));
    let home = Html::parse_document(body(&release, "/"));
    assert!(texts(&home, "nav.pager .pager-status").is_empty());
    assert_eq!(attribute(&home, "nav.pager a", "href"), ["/archive/"]);
}

#[test]
fn posts_carry_article_metadata_updated_dates_and_json_ld() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let mut revised = tagged(
        published_post(1, "Revised", "revised", 3 * 24 * 60),
        &["Rust"],
    );
    revised.updated_at = now - Duration::hours(1);
    let mut fresh = published_post(2, "Fresh", "fresh", 120);
    fresh.updated_at = now - Duration::minutes(90);
    let mut page = published_post(3, "About", "about", 30);
    page.kind = ContentKind::Page;
    let release = compile(vec![revised, fresh, page]);

    let revised = Html::parse_document(body(&release, "/revised/"));
    assert_eq!(
        attribute(
            &revised,
            "meta[property='article:published_time']",
            "content"
        ),
        ["2026-08-30T12:00:00Z"]
    );
    assert_eq!(
        attribute(
            &revised,
            "meta[property='article:modified_time']",
            "content"
        ),
        ["2026-09-02T11:00:00Z"]
    );
    assert_eq!(
        attribute(&revised, "meta[property='article:tag']", "content"),
        ["Rust"]
    );
    assert_eq!(
        attribute(&revised, "meta[property='og:site_name']", "content"),
        ["Portable writing"]
    );
    assert_eq!(
        attribute(&revised, "meta[property='og:locale']", "content"),
        ["en_US"]
    );
    assert_eq!(
        attribute(&revised, "time[itemprop=dateModified]", "datetime"),
        ["2026-09-02T11:00:00Z"]
    );
    let meta_line = texts(&revised, ".article-meta").remove(0);
    assert!(meta_line.contains("Updated"), "{meta_line}");
    assert!(meta_line.contains("min read"), "{meta_line}");
    let json_ld: serde_json::Value =
        serde_json::from_str(&texts(&revised, "script[type='application/ld+json']").remove(0))
            .unwrap();
    assert_eq!(json_ld["@type"], "BlogPosting");
    assert_eq!(json_ld["headline"], "Revised");
    assert_eq!(json_ld["datePublished"], "2026-08-30T12:00:00Z");
    assert_eq!(json_ld["author"]["name"], "Portable writing");
    assert_eq!(json_ld["keywords"][0], "Rust");

    let fresh = Html::parse_document(body(&release, "/fresh/"));
    assert!(attribute(&fresh, "time[itemprop=dateModified]", "datetime").is_empty());

    let page = Html::parse_document(body(&release, "/about/"));
    assert!(attribute(&page, "meta[property='article:published_time']", "content").is_empty());
    assert_eq!(
        attribute(&page, "meta[property='og:type']", "content"),
        ["website"]
    );

    let home = Html::parse_document(body(&release, "/"));
    let site_json: serde_json::Value =
        serde_json::from_str(&texts(&home, "script[type='application/ld+json']").remove(0))
            .unwrap();
    assert_eq!(site_json["@type"], "WebSite");
    assert!(
        site_json["potentialAction"]["target"]
            .as_str()
            .unwrap()
            .ends_with("/search/?q={search_term_string}")
    );
}

#[test]
fn json_ld_cannot_break_out_of_its_script_element() {
    let mut hostile = published_post(1, "</script><script>alert(1)</script>", "hostile", 5);
    hostile.summary = "& < >".into();
    // The fixture builder interpolates the title into body_html; in production
    // that field is sanitizer output, so keep the body inert here.
    hostile.body_html = "<p>safe</p>".into();
    let release = compile(vec![hostile]);
    let page = body(&release, "/hostile/");

    assert!(!page.contains("<script>alert"));
    let block = page
        .split("<script type=\"application/ld+json\">")
        .nth(1)
        .unwrap()
        .split("</script>")
        .next()
        .unwrap();
    assert!(block.contains("\\u003c/script"));
    assert!(!block.contains('<'));
    let parsed: serde_json::Value = serde_json::from_str(block).unwrap();
    assert_eq!(parsed["headline"], "</script><script>alert(1)</script>");
}

#[test]
fn twitter_card_downgrades_to_summary_without_a_cover() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let id = MediaId::parse("a".repeat(64)).unwrap();
    let asset = MediaAsset {
        id: id.clone(),
        original_name: "cover.png".into(),
        original_filename: format!("{id}.png"),
        mime_type: "image/png".into(),
        extension: "png".into(),
        width: 1200,
        height: 800,
        byte_size: 1234,
        alt_text: "Calm sea".into(),
        caption: String::new(),
        animated: false,
        variants: vec![MediaVariant {
            width: 480,
            height: 320,
            byte_size: 100,
            filename: format!("{id}-480w.webp"),
        }],
        created_at: now,
    };
    let mut with_cover = published_post(1, "Covered", "covered", 5);
    with_cover.cover_media_id = Some(id.to_string());
    let mut site = snapshot(vec![with_cover, published_post(2, "Bare", "bare", 10)]);
    site.media.push(asset);
    let release = SiteCompiler::embedded()
        .unwrap()
        .compile(&site, "https://writing.example", None)
        .unwrap();

    let covered = Html::parse_document(body(&release, "/covered/"));
    assert_eq!(
        attribute(&covered, "meta[name='twitter:card']", "content"),
        ["summary_large_image"]
    );
    assert_eq!(
        attribute(&covered, "meta[property='og:image']", "content"),
        [format!("https://writing.example/media/{id}.png").as_str()]
    );
    assert_eq!(attribute(&covered, "figure.cover img", "alt"), ["Calm sea"]);
    assert_eq!(
        attribute(&covered, "meta[property='og:image:width']", "content"),
        ["1200"]
    );
    assert_eq!(
        attribute(&covered, "meta[property='og:image:height']", "content"),
        ["800"]
    );
    assert_eq!(
        attribute(&covered, "meta[property='og:image:alt']", "content"),
        ["Calm sea"]
    );
    let bare = Html::parse_document(body(&release, "/bare/"));
    assert_eq!(
        attribute(&bare, "meta[name='twitter:card']", "content"),
        ["summary"]
    );
    assert!(attribute(&bare, "meta[property='og:image']", "content").is_empty());
    assert!(attribute(&bare, "meta[property='og:image:width']", "content").is_empty());
}

#[test]
fn content_pages_carry_a_table_of_contents_only_for_three_or_more_headings() {
    let mut long = published_post(1, "Long", "long", 5);
    long.body_html = "<h2 id=\"user-content-intro\"><a href=\"#user-content-intro\" class=\"anchor\" aria-label=\"Intro\"></a>Intro</h2><p>a</p>\
        <h3 id=\"user-content-detail\"><a href=\"#user-content-detail\" class=\"anchor\"></a>Detail <em>one</em></h3><p>b</p>\
        <h2 id=\"user-content-second\"><a href=\"#user-content-second\" class=\"anchor\"></a>Second</h2><p>c</p>"
        .into();
    let mut short = published_post(2, "Short", "short", 10);
    short.body_html =
        "<h2 id=\"user-content-only\">Only</h2><p>x</p><h2 id=\"user-content-two\">Two</h2>".into();
    let release = compile(vec![long, short]);

    let long = body(&release, "/long/");
    let document = Html::parse_document(long);
    assert_eq!(
        attribute(&document, "nav.toc ol li a", "href"),
        [
            "#user-content-intro",
            "#user-content-detail",
            "#user-content-second"
        ]
    );
    assert_eq!(
        texts(&document, "nav.toc > ol > li > a"),
        ["Intro", "Second"]
    );
    assert_eq!(texts(&document, "nav.toc ol ol a"), ["Detail one"]);
    assert_eq!(attribute(&document, "nav.toc", "aria-label"), ["Contents"]);
    assert!(long.find("<nav class=\"toc\"").unwrap() < long.find("<div class=\"prose\"").unwrap());

    let short = Html::parse_document(body(&release, "/short/"));
    assert!(attribute(&short, "nav.toc", "aria-label").is_empty());
}

#[test]
fn search_page_links_the_versioned_index_and_explains_the_javascript_requirement() {
    let release = compile(vec![published_post(1, "Published", "published", 5)]);
    let index = body(&release, "/assets/search-index.json");
    let expected = format!(
        "/assets/search-index.json?v={}",
        &blake3::hash(index.as_bytes()).to_hex()[..8]
    );
    let page = Html::parse_document(body(&release, "/search/"));
    assert_eq!(
        attribute(&page, "form[data-static-search]", "data-index"),
        [expected.as_str()]
    );
    let noscript = body(&release, "/search/");
    assert!(noscript.contains("<noscript>"));
    assert!(noscript.contains("JavaScript"));
    assert!(noscript.contains("href=\"/archive/\""));

    // A different index means a different URL, so no cache can serve a stale one.
    let changed = compile(vec![published_post(1, "Renamed", "published", 5)]);
    let changed_page = Html::parse_document(body(&changed, "/search/"));
    assert_ne!(
        attribute(&changed_page, "form[data-static-search]", "data-index"),
        [expected.as_str()]
    );
}

fn snapshot_in(locale: Locale, timezone: &str, contents: Vec<Content>) -> SiteSnapshotV1 {
    let mut site = snapshot(contents);
    site.settings.locale = locale;
    site.settings.timezone = timezone.into();
    site.effective_at = Utc.with_ymd_and_hms(2026, 9, 3, 0, 0, 0).unwrap();
    site
}

fn compile_snapshot(site: &SiteSnapshotV1) -> PreparedRelease {
    SiteCompiler::embedded()
        .unwrap()
        .compile(site, "https://writing.example", None)
        .unwrap()
}

fn evening_post() -> Content {
    let published = Utc.with_ymd_and_hms(2026, 9, 2, 23, 30, 0).unwrap();
    let mut post = content(
        1,
        "Evening",
        "evening",
        Publication::Public {
            publish_at: published,
        },
        0,
    );
    post.updated_at = published;
    post
}

#[test]
fn public_dates_render_in_the_site_zone_with_locale_patterns() {
    let ja = compile_snapshot(&snapshot_in(Locale::Ja, "Asia/Tokyo", vec![evening_post()]));
    let page = Html::parse_document(body(&ja, "/evening/"));
    assert_eq!(
        texts(&page, "time[itemprop=datePublished]"),
        ["2026年9月3日"]
    );
    assert_eq!(
        attribute(&page, "time[itemprop=datePublished]", "datetime"),
        ["2026-09-03T08:30:00+09:00"]
    );
    assert_eq!(
        attribute(&page, "meta[property='article:published_time']", "content"),
        ["2026-09-03T08:30:00+09:00"]
    );
    let json_ld: serde_json::Value =
        serde_json::from_str(&texts(&page, "script[type='application/ld+json']").remove(0))
            .unwrap();
    assert_eq!(json_ld["datePublished"], "2026-09-03T08:30:00+09:00");
    let archive = Html::parse_document(body(&ja, "/archive/"));
    assert_eq!(texts(&archive, ".archive-year h2"), ["2026年"]);
    assert_eq!(texts(&archive, ".archive-list time"), ["9月3日"]);
    let home = Html::parse_document(body(&ja, "/"));
    assert_eq!(texts(&home, "article.post-card time"), ["2026年9月3日"]);
    assert!(body(&ja, "/sitemap.xml").contains("<lastmod>2026-09-03</lastmod>"));
    let index: serde_json::Value =
        serde_json::from_str(body(&ja, "/assets/search-index.json")).unwrap();
    assert_eq!(index["documents"][0]["published"], "2026年9月3日");

    let en = compile_snapshot(&snapshot_in(Locale::En, "Asia/Tokyo", vec![evening_post()]));
    let page = Html::parse_document(body(&en, "/evening/"));
    assert_eq!(
        texts(&page, "time[itemprop=datePublished]"),
        ["September 3, 2026"]
    );
    let archive = Html::parse_document(body(&en, "/archive/"));
    assert_eq!(texts(&archive, ".archive-year h2"), ["2026"]);
    assert_eq!(texts(&archive, ".archive-list time"), ["Sep 3"]);

    // A UTC site keeps its old dates and the `Z` suffix.
    let utc = compile_snapshot(&snapshot_in(Locale::En, "UTC", vec![evening_post()]));
    let page = Html::parse_document(body(&utc, "/evening/"));
    assert_eq!(
        texts(&page, "time[itemprop=datePublished]"),
        ["September 2, 2026"]
    );
    assert_eq!(
        attribute(&page, "time[itemprop=datePublished]", "datetime"),
        ["2026-09-02T23:30:00Z"]
    );
}

#[test]
fn archive_years_follow_the_site_zone() {
    let published = Utc.with_ymd_and_hms(2025, 12, 31, 20, 0, 0).unwrap();
    let mut post = content(
        1,
        "Countdown",
        "countdown",
        Publication::Public {
            publish_at: published,
        },
        0,
    );
    post.updated_at = published;
    let release = compile_snapshot(&snapshot_in(Locale::En, "Asia/Tokyo", vec![post]));
    let archive = Html::parse_document(body(&release, "/archive/"));
    assert_eq!(texts(&archive, ".archive-year h2"), ["2026"]);
}

#[test]
fn author_name_feeds_feed_json_ld_and_meta_author() {
    let mut site = snapshot(vec![published_post(1, "Published", "published", 5)]);
    site.settings.author_name = "Ryo".into();
    let release = compile_snapshot(&site);
    assert!(body(&release, "/feed.xml").contains("<author><name>Ryo</name></author>"));
    let page = Html::parse_document(body(&release, "/published/"));
    assert_eq!(attribute(&page, "meta[name=author]", "content"), ["Ryo"]);
    let json_ld: serde_json::Value =
        serde_json::from_str(&texts(&page, "script[type='application/ld+json']").remove(0))
            .unwrap();
    assert_eq!(json_ld["author"]["name"], "Ryo");
    assert_eq!(json_ld["publisher"]["name"], "Ryo");

    let unnamed = compile(vec![published_post(1, "Published", "published", 5)]);
    let page = Html::parse_document(body(&unnamed, "/published/"));
    assert_eq!(
        attribute(&page, "meta[name=author]", "content"),
        ["Portable writing"]
    );
}

#[test]
fn search_and_not_found_pages_are_noindex() {
    let release = compile(vec![published_post(1, "Published", "published", 5)]);
    for path in ["/search/", "/404/"] {
        let page = Html::parse_document(body(&release, path));
        assert_eq!(
            attribute(&page, "meta[name=robots]", "content"),
            ["noindex"],
            "{path}"
        );
    }
    for path in ["/", "/published/"] {
        let page = Html::parse_document(body(&release, path));
        assert!(
            attribute(&page, "meta[name=robots]", "content").is_empty(),
            "{path}"
        );
    }
}
