use chrono::{Duration, TimeZone, Utc};
use simple_blog::{
    application::site_compiler::{PublicRedirect, SiteCompiler, SiteSnapshotV1},
    domain::{
        content::{Content, ContentId, ContentKind, Publication, Slug, Tag},
        theme::{Locale, SiteSettings},
    },
    release::{PreparedRelease, ReleaseRoute},
};

fn content(
    id: i64,
    title: &str,
    slug: &str,
    publication: Publication,
    updated_offset: i64,
) -> Content {
    let created_at = Utc.with_ymd_and_hms(2026, 9, 1, 0, 0, 0).unwrap();
    Content {
        id: ContentId::from_i64(id),
        kind: ContentKind::Post,
        title: title.into(),
        slug: Slug::parse(slug).unwrap(),
        summary: format!("Summary for {title}"),
        body_markdown: format!("# {title}\n\nBody for {title}."),
        body_html: format!("<h1>{title}</h1><p>Body for {title}.</p>"),
        tags: vec![Tag {
            name: "Rust".into(),
            slug: Slug::parse("rust").unwrap(),
        }],
        cover_media_id: None,
        seo_title: None,
        seo_description: None,
        publication,
        version: 1,
        created_at,
        updated_at: created_at + Duration::minutes(updated_offset),
    }
}

fn snapshot(contents: Vec<Content>) -> SiteSnapshotV1 {
    SiteSnapshotV1 {
        public_revision: 17,
        effective_at: Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap(),
        settings: SiteSettings {
            site_title: "Portable writing".into(),
            site_description: "A site generated by the shared core".into(),
            locale: Locale::En,
            logo_media_id: None,
            favicon_media_id: None,
            custom_css: "body { color: #222; }".into(),
        },
        navigation: Vec::new(),
        contents,
        redirects: vec![PublicRedirect {
            from: Slug::parse("before").unwrap(),
            to: Slug::parse("published").unwrap(),
        }],
        media: Vec::new(),
    }
}

fn body<'a>(release: &'a PreparedRelease, path: &str) -> &'a str {
    let ReleaseRoute::Asset { object_id, .. } = &release.manifest.routes[path] else {
        panic!("{path} is not an asset")
    };
    std::str::from_utf8(&release.objects[object_id]).unwrap()
}

#[test]
fn compiler_emits_the_complete_public_surface_without_non_visible_content() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let release = SiteCompiler::embedded()
        .unwrap()
        .compile(
            &snapshot(vec![
                content(
                    1,
                    "Published",
                    "published",
                    Publication::Public {
                        publish_at: now - Duration::hours(1),
                    },
                    1,
                ),
                content(2, "Private", "private", Publication::Draft, 2),
                content(
                    3,
                    "Future",
                    "future",
                    Publication::Public {
                        publish_at: now + Duration::hours(1),
                    },
                    3,
                ),
            ]),
            "https://writing.example",
            None,
        )
        .unwrap();

    for path in [
        "/",
        "/published/",
        "/archive/",
        "/tag/rust/",
        "/search/",
        "/feed.xml",
        "/sitemap.xml",
        "/robots.txt",
        "/404/",
        "/assets/site.css",
        "/assets/like.js",
        "/assets/prefs.js",
        "/assets/search.js",
        "/assets/search-index.json",
    ] {
        assert!(release.manifest.routes.contains_key(path), "missing {path}");
    }
    assert!(matches!(
        release.manifest.routes["/before/"],
        ReleaseRoute::Redirect { status: 301, .. }
    ));
    assert!(matches!(
        release.manifest.routes["/published"],
        ReleaseRoute::Redirect { status: 308, .. }
    ));
    assert!(!release.manifest.routes.contains_key("/private/"));
    assert!(!release.manifest.routes.contains_key("/future/"));
    assert_eq!(release.manifest.routes["/404/"].status(), Some(404));
    assert_eq!(
        release.manifest.routes["/published/"].last_modified(),
        Some(Utc.with_ymd_and_hms(2026, 9, 1, 0, 1, 0).unwrap())
    );

    let home = body(&release, "/");
    assert!(home.contains("Published"));
    assert!(!home.contains("Private"));
    assert!(!home.contains("Future"));
    assert!(home.contains("https://writing.example/"));
    assert!(body(&release, "/feed.xml").contains("Body for Published"));
    assert!(body(&release, "/sitemap.xml").contains("/published/"));
    assert!(body(&release, "/assets/search-index.json").contains("Published"));
}

#[test]
fn compiler_output_is_deterministic_for_equivalent_snapshot_orderings() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let first = content(
        1,
        "First",
        "first",
        Publication::Public {
            publish_at: now - Duration::hours(2),
        },
        1,
    );
    let second = content(
        2,
        "Second",
        "second",
        Publication::Public {
            publish_at: now - Duration::hours(1),
        },
        2,
    );
    let compiler = SiteCompiler::embedded().unwrap();

    let ordered = compiler
        .compile(
            &snapshot(vec![first.clone(), second.clone()]),
            "https://writing.example",
            None,
        )
        .unwrap();
    let reversed = compiler
        .compile(
            &snapshot(vec![second, first]),
            "https://writing.example/",
            None,
        )
        .unwrap();

    assert_eq!(ordered.id, reversed.id);
    assert_eq!(ordered.manifest_bytes, reversed.manifest_bytes);
    assert_eq!(ordered.objects, reversed.objects);
}

#[test]
fn compiler_reuses_unchanged_objects_without_changing_clean_build_semantics() {
    let now = Utc.with_ymd_and_hms(2026, 9, 2, 12, 0, 0).unwrap();
    let compiler = SiteCompiler::embedded().unwrap();
    let original = content(
        1,
        "Original",
        "original",
        Publication::Public {
            publish_at: now - Duration::hours(1),
        },
        1,
    );
    let base = compiler
        .compile(
            &snapshot(vec![original.clone()]),
            "https://writing.example",
            None,
        )
        .unwrap();
    let mut changed = original;
    changed.title = "Changed".into();
    changed.body_html = "<p>Changed body</p>".into();
    changed.updated_at += Duration::minutes(1);
    let mut next_snapshot = snapshot(vec![changed]);
    next_snapshot.public_revision = 18;

    let incremental = compiler
        .compile(
            &next_snapshot,
            "https://writing.example",
            Some(&base.manifest),
        )
        .unwrap();
    let clean = compiler
        .compile(&next_snapshot, "https://writing.example", None)
        .unwrap();

    assert_eq!(incremental.id, clean.id);
    assert_eq!(incremental.manifest, clean.manifest);
    assert!(incremental.objects.len() < clean.objects.len());
}
